[package]
name = "zenvaformers-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11"
godot_sane_defaults = { path = "../../../../factory/godot_sane_defaults" }
